// quotes.js
const quotes = [
  { text: "The best way to get started is to quit talking and begin doing.", author: "Walt Disney", category: "Motivation" },
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon", category: "Life" },
  { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein", category: "Inspiration" },
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde", category: "Wisdom" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt", category: "Motivation" },
  { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill", category: "Success" },
  { text: "Happiness depends upon ourselves.", author: "Aristotle", category: "Happiness" },
  { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington", category: "Kindness" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James", category: "Positivity" },
  { text: "What we think, we become.", author: "Buddha", category: "Mindset" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein", category: "Wisdom" },
  { text: "Everything you can imagine is real.", author: "Pablo Picasso", category: "Creativity" },
  { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey", category: "Life" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela", category: "Motivation" },
  { text: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman", category: "Positivity" },
  { text: "Opportunities don't happen. You create them.", author: "Chris Grosser", category: "Success" },
  { text: "Don’t let yesterday take up too much of today.", author: "Will Rogers", category: "Life" },
  { text: "Dream big and dare to fail.", author: "Norman Vaughan", category: "Dreams" },
  { text: "Dream big and never ever fail.", author: "Norman Vaughan", category: "Dreams" },
  { text: "Everything has beauty, but not everyone sees it.", author: "Confucius", category: "Wisdom" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", category: "Motivation" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", category: "Inspiration" },
  { text: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll", category: "Life" },
  { text: "The purpose of our lives is to be happy.", author: "Dalai Lama", category: "Happiness" },
  { text: "Get busy living or get busy dying.", author: "Stephen King", category: "Life" },
  { text: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy", category: "Motivation" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", category: "Motivation" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", category: "Success" },
  { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett", category: "Success" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis", category: "Dreams" },
  { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt", category: "Inspiration" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", category: "Perseverance" },
  { text: "Everything you can imagine is real.", author: "Pablo Picasso", category: "Creativity" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky", category: "Motivation" },
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon", category: "Life" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln", category: "Inspiration" },
  { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill", category: "Success" },
  { text: "Happiness depends upon ourselves.", author: "Aristotle", category: "Happiness" },
  { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington", category: "Kindness" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James", category: "Positivity" },
  { text: "What we think, we become.", author: "Buddha", category: "Mindset" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein", category: "Wisdom" },
  { text: "Everything you can imagine is real.", author: "Pablo Picasso", category: "Creativity" },
  { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey", category: "Life" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela", category: "Motivation" },
  { text: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman", category: "Positivity" },
  { text: "Opportunities don't happen. You create them.", author: "Chris Grosser", category: "Success" },
  { text: "Don’t let yesterday take up too much of today.", author: "Will Rogers", category: "Life" },
  { text: "Dream big and dare to fail.", author: "Norman Vaughan", category: "Dreams" },
  { text: "Dream big and never ever fail.", author: "Norman Vaughan", category: "Dreams" },
  { text: "Everything has beauty, but not everyone sees it.", author: "Confucius", category: "Wisdom" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", category: "Motivation" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", category: "Inspiration" },
  { text: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll", category: "Life" },
  { text: "The purpose of our lives is to be happy.", author: "Dalai Lama", category: "Happiness" },
  { text: "Get busy living or get busy dying.", author: "Stephen King", category: "Life" },
  { text: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy", category: "Motivation" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", category: "Motivation" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", category: "Success" },
  { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett", category: "Success" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis", category: "Dreams" },
  { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt", category: "Inspiration" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", category: "Perseverance" },
  { text: "Everything you can imagine is real.", author: "Pablo Picasso", category: "Creativity" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky", category: "Motivation" },
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon", category: "Life" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln", category: "Inspiration" },
  { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill", category: "Success" },
  { text: "Happiness depends upon ourselves.", author: "Aristotle", category: "Happiness" },
  { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington", category: "Kindness" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James", category: "Positivity" },
  { text: "What we think, we become.", author: "Buddha", category: "Mindset" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein", category: "Wisdom" },
  { text: "Everything you can imagine is real.", author: "Pablo Picasso", category: "Creativity" },
    { text: "When you believe in a thing, believe in it all the way, implicitly and unquestionable.", author: "Walt Disney", category: "Motivation" },
  { text: "It's kind of fun to do the impossible.", author: "Walt Disney", category: "Inspiration" },
  { text: "Laughter is timeless, imagination has no age, and dreams are forever.", author: "Walt Disney", category: "Life" },
  { text: "Everything will be okay in the end. If it's not okay, it's not the end.", author: "John Lennon", category: "Hope" },
  { text: "Count your age by friends, not years. Count your life by smiles, not tears.", author: "John Lennon", category: "Life" },
  { text: "Music is everybody's possession. It's only publishers who think that people own it.", author: "John Lennon", category: "Creativity" },
  { text: "Life is like riding a bicycle. To keep your balance you must keep moving.", author: "Albert Einstein", category: "Motivation" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein", category: "Courage" },
  { text: "Education is what remains after one has forgotten what one has learned in school.", author: "Albert Einstein", category: "Education" },
  { text: "I can resist everything except temptation.", author: "Oscar Wilde", category: "Humor" },
  { text: "To love oneself is the beginning of a lifelong romance.", author: "Oscar Wilde", category: "Self-love" },
  { text: "A cynic knows the price of everything and the value of nothing.", author: "Oscar Wilde", category: "Wisdom" },
  { text: "Nothing in the world is worth having or worth doing unless it means effort.", author: "Theodore Roosevelt", category: "Motivation" },
  { text: "Far and away the best prize that life has to offer is the chance to work hard at work worth doing.", author: "Theodore Roosevelt", category: "Life" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt", category: "Action" },
  { text: "To improve is to change; to be perfect is to change often.", author: "Winston Churchill", category: "Change" },
  { text: "Attitude is a little thing that makes a big difference.", author: "Winston Churchill", category: "Attitude" },
  { text: "Success is stumbling from failure to failure with no loss of enthusiasm.", author: "Winston Churchill", category: "Success" },
  { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle", category: "Wisdom" },
  { text: "Happiness is the meaning and the purpose of life, the whole aim and end of human existence.", author: "Aristotle", category: "Happiness" },
  { text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle", category: "Mindset" },
  { text: "Three things cannot be long hidden: the sun, the moon, and the truth.", author: "Buddha", category: "Truth" },
  { text: "The mind is everything. What you think you become.", author: "Buddha", category: "Mindset" },
  { text: "No one saves us but ourselves. No one can and no one may. We ourselves must walk the path.", author: "Buddha", category: "Self-help" },
  { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey", category: "Life" },
  { text: "The biggest adventure you can take is to live the life of your dreams.", author: "Oprah Winfrey", category: "Dreams" },
  { text: "Surround yourself with only people who are going to lift you higher.", author: "Oprah Winfrey", category: "Motivation" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs", category: "Innovation" },
  { text: "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.", author: "Steve Jobs", category: "Motivation" },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs", category: "Wisdom" },
  { text: "Art is the lie that enables us to realize the truth.", author: "Pablo Picasso", category: "Art" },
  { text: "Every child is an artist. The problem is how to remain an artist once we grow up.", author: "Pablo Picasso", category: "Creativity" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso", category: "Success" },
  { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama", category: "Happiness" },
  { text: "Remember that sometimes not getting what you want is a wonderful stroke of luck.", author: "Dalai Lama", category: "Life" },
  { text: "Be kind whenever possible. It is always possible.", author: "Dalai Lama", category: "Kindness" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela", category: "Motivation" },
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela", category: "Education" },
  { text: "I never lose. I either win or learn.", author: "Nelson Mandela", category: "Wisdom" },
  { text: "Do not watch the clock. Do what it does. Keep going.", author: "Sam Levenson", category: "Motivation" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain", category: "Motivation" },
  { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi", category: "Inspiration" },
  { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein", category: "Inspiration" },
  { text: "If opportunity doesn't knock, build a door.", author: "Milton Berle", category: "Success" },
  { text: "The harder I work, the luckier I get.", author: "Samuel Goldwyn", category: "Success" },
  { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt", category: "Courage" },
  { text: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh", category: "Motivation" },
  { text: "Courage is resistance to fear, mastery of fear—not absence of fear.", author: "Mark Twain", category: "Courage" },
  { text: "Believe in yourself and all that you are.", author: "Christian D. Larson", category: "Motivation" },
    { text: "All our dreams can come true if we have the courage to pursue them.", author: "Walt Disney", category: "Motivation" },
  { text: "The way to get started is to stop talking and start doing.", author: "Walt Disney", category: "Action" },
  { text: "Around here, we don't look backwards for very long.", author: "Walt Disney", category: "Inspiration" },
  { text: "Reality leaves a lot to the imagination.", author: "John Lennon", category: "Creativity" },
  { text: "You don't need anybody to tell you who you are or what you are.", author: "John Lennon", category: "Self-awareness" },
  { text: "Time you enjoy wasting, was not wasted.", author: "John Lennon", category: "Life" },
  { text: "Imagination is more important than knowledge.", author: "Albert Einstein", category: "Creativity" },
  { text: "Try not to become a man of success, but rather try to become a man of value.", author: "Albert Einstein", category: "Wisdom" },
  { text: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Albert Einstein", category: "Inspiration" },
  { text: "Experience is merely the name men gave to their mistakes.", author: "Oscar Wilde", category: "Life" },
  { text: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde", category: "Motivation" },
  { text: "The truth is rarely pure and never simple.", author: "Oscar Wilde", category: "Wisdom" },
  { text: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt", category: "Motivation" },
  { text: "In any moment of decision, the best thing you can do is the right thing.", author: "Theodore Roosevelt", category: "Action" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt", category: "Motivation" },
  { text: "Courage is rightly esteemed the first of human qualities.", author: "Winston Churchill", category: "Courage" },
  { text: "Continuous effort—not strength or intelligence—is the key to unlocking our potential.", author: "Winston Churchill", category: "Success" },
  { text: "To improve is to change; to be perfect is to change often.", author: "Winston Churchill", category: "Wisdom" },
  { text: "Happiness is the highest good.", author: "Aristotle", category: "Happiness" },
  { text: "Pleasure in the job puts perfection in the work.", author: "Aristotle", category: "Motivation" },
  { text: "Educating the mind without educating the heart is no education at all.", author: "Aristotle", category: "Wisdom" },
  { text: "Success is to be measured not so much by the position that one has reached as by the obstacles overcome.", author: "Booker T. Washington", category: "Success" },
  { text: "Associate yourself with people of good quality, for it is better to be alone than in bad company.", author: "Booker T. Washington", category: "Advice" },
  { text: "Nothing ever comes to one that is worth having except as a result of hard work.", author: "Booker T. Washington", category: "Work" },
  { text: "The greatest discovery of my generation is that a human being can alter his life by altering his attitudes.", author: "William James", category: "Mindset" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James", category: "Positivity" },
  { text: "The art of being wise is knowing what to overlook.", author: "William James", category: "Wisdom" },
  { text: "Peace comes from within. Do not seek it without.", author: "Buddha", category: "Mindset" },
  { text: "No one saves us but ourselves.", author: "Buddha", category: "Wisdom" },
  { text: "Health is the greatest gift, contentment the greatest wealth.", author: "Buddha", category: "Happiness" },
  { text: "Everything you can imagine is real.", author: "Pablo Picasso", category: "Creativity" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso", category: "Action" },
  { text: "Inspiration exists, but it has to find you working.", author: "Pablo Picasso", category: "Inspiration" },
  { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey", category: "Life" },
  { text: "The biggest adventure you can take is to live the life of your dreams.", author: "Oprah Winfrey", category: "Dreams" },
  { text: "Surround yourself with only people who are going to lift you higher.", author: "Oprah Winfrey", category: "Motivation" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela", category: "Motivation" },
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela", category: "Education" },
  { text: "A good head and a good heart are always a formidable combination.", author: "Nelson Mandela", category: "Wisdom" },
  { text: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman", category: "Positivity" },
  { text: "Be curious, not judgmental.", author: "Walt Whitman", category: "Mindset" },
  { text: "Happiness is a perfume you cannot pour on others without getting a few drops on yourself.", author: "Walt Whitman", category: "Happiness" },
  { text: "Opportunities don't happen. You create them.", author: "Chris Grosser", category: "Success" },
  { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Chris Grosser", category: "Success" },
  { text: "Action is the real measure of intelligence.", author: "Chris Grosser", category: "Action" },
  { text: "Don’t let yesterday take up too much of today.", author: "Will Rogers", category: "Life" },
  { text: "Even if you are on the right track, you’ll get run over if you just sit there.", author: "Will Rogers", category: "Motivation" },
  { text: "The road to success is always under construction.", author: "Will Rogers", category: "Success" },
  { text: "Dream big and dare to fail.", author: "Norman Vaughan", category: "Dreams" },
  { text: "Do one thing every day that scares you.", author: "Norman Vaughan", category: "Courage" },
  { text: "It's not the mountain we conquer but ourselves.", author: "Norman Vaughan", category: "Life" },
  { text: "Everything has beauty, but not everyone sees it.", author: "Confucius", category: "Wisdom" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", category: "Perseverance" },
  { text: "When it is obvious that the goals cannot be reached, don't adjust the goals, adjust the action steps.", author: "Confucius", category: "Action" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", category: "Inspiration" },
  { text: "Setting goals is the first step in turning the invisible into the visible.", author: "Tony Robbins", category: "Success" },
  { text: "Your past does not equal your future.", author: "Tony Robbins", category: "Mindset" },
  { text: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll", category: "Life" },
  { text: "Attitude is a little thing that makes a big difference.", author: "Charles R. Swindoll", category: "Mindset" },
  { text: "The best preparation for tomorrow is doing your best today.", author: "Charles R. Swindoll", category: "Action" },
  { text: "The purpose of our lives is to be happy.", author: "Dalai Lama", category: "Happiness" },
  { text: "Be kind whenever possible. It is always possible.", author: "Dalai Lama", category: "Kindness" },
  { text: "Judge your success by what you had to give up in order to get it.", author: "Dalai Lama", category: "Wisdom" },
  { text: "Get busy living or get busy dying.", author: "Stephen King", category: "Life" },
  { text: "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", author: "Stephen King", category: "Motivation" },
  { text: "You can, you should, and if you’re brave enough to start, you will.", author: "Stephen King", category: "Courage" }
];

module.exports = quotes;
